package com.example.data

import java.util.UUID
import kotlin.math.abs
import kotlin.math.min

/**
 * Explicit tiers representing the provenance and environment of evidence collected
 * by the Closed Loop Intelligence system.
 */
enum class EvidenceTier {
    /** Live user interaction evidence collected from actual production environments. */
    PRODUCTION,
    /** Evidence gathered from controlled A/B tests, synthetic cohorts, or beta user groups. */
    EXPERIMENTAL,
    /** Evidence generated by predictive models, Monte Carlo simulations, or offline benchmarks. */
    SIMULATION
}

/**
 * Indicates whether a target metric represents a valid, measurable improvement over baseline.
 */
enum class TargetValidity {
    /** Target score represents a meaningful improvement over baseline. */
    VALID,
    /** Target score is invalid or unachievable. */
    INVALID_TARGET,
    /** Target score equals the baseline score; no net change is specified by the target. */
    UNCHANGED_TARGET
}

/**
 * Deterministic, evidence-aware outcome classifications for Closed Loop evaluations.
 */
enum class OutcomeClassification {
    /** Insufficient or zero production evidence available to draw conclusions. */
    INSUFFICIENT_DATA,
    /** Baseline metric has been recorded, but post-change metrics are pending. */
    BASELINE_ESTABLISHED,
    /** Measured score is unchanged relative to baseline (within tolerance). */
    NO_MEASURABLE_CHANGE,
    /** Statistically verified improvement supported by sufficient production evidence. */
    IMPROVEMENT_DETECTED,
    /** High-confidence, substantial improvement confirmed by production evidence. */
    SIGNIFICANT_IMPROVEMENT,
    /** Measured production performance is statistically worse than baseline. */
    REGRESSION_DETECTED,
    /** Experimental or simulation data exists, but production outcome cannot be confirmed. */
    EXPERIMENT_INCONCLUSIVE
}

/**
 * Represents a single evidence record collected for metric evaluation.
 */
data class EvidenceRecord(
    val id: String = UUID.randomUUID().toString(),
    val tier: EvidenceTier,
    val sampleCount: Int,
    val score: Double,
    val quality: Double = 1.0, // Scale 0.0 to 1.0
    val source: String = "Unknown",
    val timestamp: Long = System.currentTimeMillis(),
    val confidenceContribution: Double = 0.0,
    val isEligibleForProductionOutcome: Boolean = (tier == EvidenceTier.PRODUCTION && sampleCount > 0),
    val associatedManifestId: String? = null
)

/**
 * Complete evidence-aware Closed Loop Intelligence evaluation report.
 */
data class ClosedLoopReport(
    val id: String = UUID.randomUUID().toString(),
    val timestamp: Long = System.currentTimeMillis(),
    val baselineScore: Double,
    val measuredScore: Double,
    val targetScore: Double,
    val targetValidity: TargetValidity,
    val outcomeClassification: OutcomeClassification,
    val productionEvidence: List<EvidenceRecord> = emptyList(),
    val experimentalEvidence: List<EvidenceRecord> = emptyList(),
    val simulationEvidence: List<EvidenceRecord> = emptyList(),
    val productionSampleCount: Int = 0,
    val experimentalSampleCount: Int = 0,
    val simulationSampleCount: Int = 0,
    val productionEvidenceQuality: Double = 0.0,
    val experimentalEvidenceQuality: Double = 0.0,
    val simulationEvidenceQuality: Double = 0.0,
    val productionConfidence: Double = 0.0,
    val experimentalConfidence: Double = 0.0,
    val simulationConfidence: Double = 0.0,
    val overallConfidence: Double = 0.0,
    val statisticalStrength: Double = 0.0,
    val behaviorConsistency: Double = 0.0,
    val knownFacts: List<String> = emptyList(),
    val inferences: List<String> = emptyList(),
    val simulatedFindings: List<String> = emptyList(),
    val experimentalFindings: List<String> = emptyList(),
    val unknowns: List<String> = emptyList(),
    val productionImprovementEstablished: Boolean = false,
    val productionRegressionEstablished: Boolean = false,
    val summaryMessage: String = ""
)

/**
 * Evaluates strategy metrics and evidence records using strict evidence integrity rules.
 */
object ClosedLoopEngine {
    private const val DEFAULT_EPSILON = 0.001
    private const val MIN_PRODUCTION_SAMPLES_THRESHOLD = 5

    /**
     * Evaluates metrics and evidence records to produce an evidence-aware report.
     *
     * @param baselineScore Baseline score before intervention.
     * @param measuredScore Measured score after intervention.
     * @param targetScore Projected/target score.
     * @param evidenceList All evidence records collected.
     * @param minProductionSamples Minimum production samples needed for production conclusions.
     * @param epsilon Comparison tolerance for floating point metric comparisons.
     */
    fun evaluate(
        baselineScore: Double,
        measuredScore: Double,
        targetScore: Double,
        evidenceList: List<EvidenceRecord>,
        minProductionSamples: Int = MIN_PRODUCTION_SAMPLES_THRESHOLD,
        epsilon: Double = DEFAULT_EPSILON
    ): ClosedLoopReport {
        // 1. Separate evidence by tier
        val productionRecords = evidenceList.filter { it.tier == EvidenceTier.PRODUCTION }
        val experimentalRecords = evidenceList.filter { it.tier == EvidenceTier.EXPERIMENTAL }
        val simulationRecords = evidenceList.filter { it.tier == EvidenceTier.SIMULATION }

        // 2. Aggregate sample counts
        val prodCount = productionRecords.sumOf { it.sampleCount }
        val expCount = experimentalRecords.sumOf { it.sampleCount }
        val simCount = simulationRecords.sumOf { it.sampleCount }

        // 3. Compute weighted qualities
        val prodQuality = if (prodCount > 0) {
            productionRecords.sumOf { it.quality * it.sampleCount } / prodCount
        } else 0.0

        val expQuality = if (expCount > 0) {
            experimentalRecords.sumOf { it.quality * it.sampleCount } / expCount
        } else 0.0

        val simQuality = if (simCount > 0) {
            simulationRecords.sumOf { it.quality * it.sampleCount } / simCount
        } else 0.0

        // 4. Target validity rule (Rule C)
        val targetDiff = targetScore - baselineScore
        val targetValidity = when {
            abs(targetDiff) <= epsilon -> TargetValidity.UNCHANGED_TARGET
            targetDiff < -epsilon -> TargetValidity.INVALID_TARGET
            else -> TargetValidity.VALID
        }

        // 5. Compute confidence per tier
        // PRODUCTION CONFIDENCE MUST BE 0.0 IF prodCount == 0!
        val prodConfidence = if (prodCount == 0) {
            0.0
        } else {
            val sampleFactor = min(1.0, prodCount.toDouble() / 50.0)
            sampleFactor * prodQuality
        }

        val expConfidence = if (expCount == 0) {
            0.0
        } else {
            val sampleFactor = min(1.0, expCount.toDouble() / 100.0)
            sampleFactor * expQuality * 0.8 // Discounted compared to production
        }

        val simConfidence = if (simCount == 0) {
            0.0
        } else {
            val sampleFactor = min(1.0, simCount.toDouble() / 500.0)
            sampleFactor * simQuality * 0.5 // Heavily discounted compared to empirical
        }

        val overallConfidence = prodConfidence // Overall production conclusion confidence matches prodConfidence

        // 6. Classification & Production Flags (Rules A, B, D, E)
        val scoreDiff = measuredScore - baselineScore
        var prodImprovementEstablished = false
        var prodRegressionEstablished = false

        val classification: OutcomeClassification = when {
            // Rule A: Zero or insufficient production evidence
            prodCount == 0 -> {
                prodImprovementEstablished = false
                prodRegressionEstablished = false
                if (expCount == 0 && simCount == 0) {
                    OutcomeClassification.INSUFFICIENT_DATA
                } else {
                    OutcomeClassification.EXPERIMENT_INCONCLUSIVE
                }
            }

            // Production sample count below threshold required for statistical confirmation
            prodCount < minProductionSamples -> {
                prodImprovementEstablished = false
                prodRegressionEstablished = false
                OutcomeClassification.INSUFFICIENT_DATA
            }

            // Rule B: Measured score equals baseline score
            abs(scoreDiff) <= epsilon -> {
                prodImprovementEstablished = false
                prodRegressionEstablished = false
                OutcomeClassification.NO_MEASURABLE_CHANGE
            }

            // Rule D: Measured production score worse than baseline
            scoreDiff < -epsilon -> {
                prodImprovementEstablished = false
                prodRegressionEstablished = true
                OutcomeClassification.REGRESSION_DETECTED
            }

            // Rule E: Measured production score better than baseline with sufficient samples
            scoreDiff > epsilon -> {
                prodImprovementEstablished = true
                prodRegressionEstablished = false
                if (scoreDiff >= 10.0 && prodConfidence >= 0.7) {
                    OutcomeClassification.SIGNIFICANT_IMPROVEMENT
                } else {
                    OutcomeClassification.IMPROVEMENT_DETECTED
                }
            }

            else -> OutcomeClassification.INSUFFICIENT_DATA
        }

        // 7. Structured Fact / Inference Extraction (Step 7 requirement)
        val knownFacts = mutableListOf<String>()
        knownFacts.add("Production baseline score established at ${"%.2f".format(baselineScore)}.")
        knownFacts.add("Production measured score recorded at ${"%.2f".format(measuredScore)}.")
        if (targetValidity == TargetValidity.UNCHANGED_TARGET) {
            knownFacts.add("Target score equals baseline score (${"%.2f".format(targetScore)}). Target specifies zero net change.")
        } else if (targetValidity == TargetValidity.INVALID_TARGET) {
            knownFacts.add("Target score (${"%.2f".format(targetScore)}) is below baseline (${"%.2f".format(baselineScore)}).")
        }
        if (prodCount > 0) {
            knownFacts.add("Production evidence contains $prodCount sample(s) across ${productionRecords.size} record(s).")
        } else {
            knownFacts.add("Zero production evidence samples collected (production_evidence_samples = 0).")
        }

        val inferences = mutableListOf<String>()
        if (prodCount == 0) {
            inferences.add("Production effect is unverified; experimental or simulation trends cannot be assumed to hold in live production.")
        } else {
            inferences.add("Observed production shift (${"%.2f".format(scoreDiff)}) reflects live user workload under recorded conditions.")
        }

        val experimentalFindings = mutableListOf<String>()
        if (expCount > 0) {
            val avgExpScore = experimentalRecords.sumOf { it.score * it.sampleCount } / expCount
            experimentalFindings.add("Experimental trials: $expCount samples across ${experimentalRecords.size} run(s), weighted score: ${"%.2f".format(avgExpScore)}.")
        } else {
            experimentalFindings.add("No experimental evidence recorded.")
        }

        val simulatedFindings = mutableListOf<String>()
        if (simCount > 0) {
            val avgSimScore = simulationRecords.sumOf { it.score * it.sampleCount } / simCount
            simulatedFindings.add("Simulation runs: $simCount samples across ${simulationRecords.size} run(s), weighted score: ${"%.2f".format(avgSimScore)}.")
        } else {
            simulatedFindings.add("No simulation evidence recorded.")
        }

        val unknowns = mutableListOf<String>()
        if (prodCount == 0) {
            unknowns.add("Actual production user experience and live performance metrics are UNKNOWN.")
        }
        if (targetValidity == TargetValidity.UNCHANGED_TARGET) {
            unknowns.add("Expected long-term value creation is UNKNOWN because target metric matches baseline.")
        }
        unknowns.add("Persistence of observed metric stability over extended quarterly execution windows.")

        // 8. Human-readable summary
        val summaryText = buildString {
            if (prodCount == 0) {
                append("PRODUCTION EVIDENCE MISSING (0 samples). ")
                append("Production improvement CANNOT be established. ")
                append("Outcome classified as ${classification.name}.")
            } else {
                append("Production evidence available ($prodCount samples). ")
                append("Outcome classified as ${classification.name}. ")
                if (prodImprovementEstablished) {
                    append("Production improvement ESTABLISHED (+${"%.2f".format(scoreDiff)} vs baseline).")
                } else if (prodRegressionEstablished) {
                    append("Production regression ESTABLISHED (${"%.2f".format(scoreDiff)} vs baseline).")
                } else {
                    append("No statistically significant production change detected.")
                }
            }
        }

        return ClosedLoopReport(
            baselineScore = baselineScore,
            measuredScore = measuredScore,
            targetScore = targetScore,
            targetValidity = targetValidity,
            outcomeClassification = classification,
            productionEvidence = productionRecords,
            experimentalEvidence = experimentalRecords,
            simulationEvidence = simulationRecords,
            productionSampleCount = prodCount,
            experimentalSampleCount = expCount,
            simulationSampleCount = simCount,
            productionEvidenceQuality = prodQuality,
            experimentalEvidenceQuality = expQuality,
            simulationEvidenceQuality = simQuality,
            productionConfidence = prodConfidence,
            experimentalConfidence = expConfidence,
            simulationConfidence = simConfidence,
            overallConfidence = overallConfidence,
            statisticalStrength = if (prodCount >= minProductionSamples) min(1.0, prodCount / 100.0) else 0.0,
            behaviorConsistency = if (prodCount > 0) prodQuality else 0.0,
            knownFacts = knownFacts,
            inferences = inferences,
            simulatedFindings = simulatedFindings,
            experimentalFindings = experimentalFindings,
            unknowns = unknowns,
            productionImprovementEstablished = prodImprovementEstablished,
            productionRegressionEstablished = prodRegressionEstablished,
            summaryMessage = summaryText
        )
    }
}
